# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_in.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Log(object):
    def __init__(self, Client):
        self.client = Client

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:rgb(18, 18, 18);\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 0, 721, 381))
        self.label.setPixmap(QtGui.QPixmap(":/photos/gamelogo.png"))
        self.label.setObjectName("label")
        self.username_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.username_2.setGeometry(QtCore.QRect(220, 470, 351, 71))
        self.username_2.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                      "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.username_2.setObjectName("username_2")
        self.username = QtWidgets.QTextEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(220, 390, 351, 71))
        self.username.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                    "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;\n"
                                    "")
        self.username.setObjectName("username")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 470, 121, 71))
        self.pushButton.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                      "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(600, 440, 121, 20))
        self.checkBox.setStyleSheet(";background-color: rgb(253, 253, 253);")
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.check_for_input(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(
            _translate("MainWindow", "<html><head/><body><p><img src=\":/photos2/logo.png\"/></p></body></html>"))
        self.username_2.setHtml(_translate("MainWindow",
                                           "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                           "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                           "p, li { white-space: pre-wrap; }\n"
                                           "</style></head><body style=\" font-family:\'Magneto\'; font-size:35px; font-weight:72; font-style:normal;\">\n"
                                           "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:35px;\">enter password</span></p></body></html>"))
        self.username.setHtml(_translate("MainWindow",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'Magneto\'; font-size:35px; font-weight:72; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:35px;\">enter username</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "log-in"))
        self.checkBox.setText(_translate("MainWindow", "I am not a robot"))

    def check_for_input(self, MainWindow):
        self.pushButton.clicked.connect(lambda: self.log_in_pressed(MainWindow))

    def log_in_pressed(self, MainWindow):
        self.client.username = self.username.toPlainText()
        self.client.password = self.username_2.toPlainText()
        MainWindow.close()

import images


def show_window(window):
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    window.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())



